apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-apic
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/apic/namespace
    repoURL: https://github.com/divyakamathorg/gitops-test-cp4i-instance
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
